// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBB40aBdXj2obXGWZPZDL3wrqDW3ssWd1w',
    appId: '1:240506779182:android:2a779ac833c4e4b82f11bf',
    messagingSenderId: '240506779182',
    projectId: 'weightwatcher-59b4e',
    storageBucket: 'weightwatcher-59b4e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaZpaQPAE5xWuu-81lqd2hTpIE4CSEUig',
    appId: '1:240506779182:ios:02e4652592d7b4da2f11bf',
    messagingSenderId: '240506779182',
    projectId: 'weightwatcher-59b4e',
    storageBucket: 'weightwatcher-59b4e.appspot.com',
    iosBundleId: 'com.shamilla.weightwatcher',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBh-0Gquz5AecbcA8C0pbvN3v9ZcyAX1og',
    appId: '1:240506779182:web:47a24408a63e21a42f11bf',
    messagingSenderId: '240506779182',
    projectId: 'weightwatcher-59b4e',
    authDomain: 'weightwatcher-59b4e.firebaseapp.com',
    storageBucket: 'weightwatcher-59b4e.appspot.com',
    measurementId: 'G-C5ZLLZLPY5',
  );

}